CREATE TABLE `rest_with_asp_net_udemy`.`persons` (
  `Id` INT(10) UNSIGNED NULL DEFAULT NULL, 
  `FirstName` VARCHAR(50) NULL DEFAULT NULL, 
  `LastName` VARCHAR(50) NULL DEFAULT NULL, 
  `Address` VARCHAR(50) NULL DEFAULT NULL, 
  `Gender` VARCHAR(50) NULL DEFAULT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
